apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
        - name: express-container
          image: liorsoffer/express-app # Replace with your Express image
          ports:
            - containerPort: 3000 # Match your Express app's listening port
---
apiVersion: v1
kind: Service
metadata:
  name: express-service
spec:
  selector:
    app: express
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: ClusterIP # Internal service within the cluster
