apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
        - name: react-container
          image: liorsoffer/react-app # Replace with your React image
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_URL
              value: "http://express-service/api" # Pointing to Express Service
---
apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  selector:
    app: react
  ports:
    - protocol: TCP
      port: 80 # Exposing on port 80 for external access
      targetPort: 3000 # React app listens on port 3000
  type: NodePort # Exposes React app externally
